export const bills = [
  {
    id: 1,
    factorNumber: 9873546,
    factorDate: 2023,
    customerName: "علی منیری",
    factorPrice: 2000,
    factorType: "همکاری",
    deliveryType: "پیک",
  },
  {
    id: 2,
    factorNumber: 9873782,
    factorDate: 2023,
    customerName: "علی منیری",
    factorPrice: 2000,
    factorType: "همکاری",
    deliveryType: "پیک",
  },
  {
    id: 3,
    factorNumber: 9873852,
    factorDate: 2023,
    customerName: "علی منیری",
    factorPrice: 2000,
    factorType: "همکاری",
    deliveryType: "پیک",
  },
  {
    id: 4,
    factorNumber: 9873123,
    factorDate: 2023,
    customerName: "علی منیری",
    factorPrice: 2000,
    factorType: "همکاری",
    deliveryType: "پیک",
  },
  {
    id: 5,
    factorNumber: 9873602,
    factorDate: 2023,
    customerName: "علی منیری",
    factorPrice: 2000,
    factorType: "همکاری",
    deliveryType: "پیک",
  },
];
